name: Publish to reeves.nl
on:
  workflow_dispatch:
jobs:
  build:
    name: Publish to reeves.nl
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - run: rm -f ./public/**/*.js.map
      - run: rm -f ./public/**/*.mdx
      - run: rm -f ./public/**/*.md
      - run: rm -f ./public/**/*.tsx

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './public/'
          server-dir: 'public_html/'
